[package]
name = "deploykit-gui"
version = "0.10.5"
description = "Deploykit GUI frontend"
authors = ["you"]
license = "MIT"
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }
vergen-gix = { version = "10.0.3", default-features = false }
vergen = { version = "10.0.3", default-features = false }

[dependencies]
tauri = { version = "2.0.0", features = [] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
zbus = { version = "5.1.0", default-features = false, features = ["tokio"] }
tokio = { version = "1.42.0", features = ["rt-multi-thread", "process"] }
eyre = "0.6.12"
nom = "8"
url = "2.5.2"
reqwest = { version = "0.13", default-features = false, features = [
    "json",
    "rustls-no-provider",
] }
thiserror = "2"
libc = "0.2.159"
futures = "0.3.30"
rand = "0.10"
axum = "0.8"
tower-http = { version = "0.7", features = ["fs", "cors"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
x11rb = "0.14"
sysinfo = "0.39"
tauri-plugin-shell = "2.0.0"
tauri-plugin-dialog = "2.0.0"
tauri-plugin-cli = "2.0.0"
libaosc = { version = "0.4", default-features = false, features = ["arch"] }
rustls = { version = "0.23", default-features = false, features = [
    "ring",
    "tls12",
] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
devtools = ["tauri/devtools"]

[lib]
name = "app_lib"
# FIXME: Remove 'lib': https://github.com/tauri-apps/tauri/issues/9547
crate-type = ["staticlib", "cdylib", "rlib"]
